---
title: "Muziek Database"
author: "Connor Whalen"
date: "2024-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install packages. 
```{r}
install.packages("tidyverse")
install.packages("janitor")
install.packages("ggeffects")
install.packages("ggpubr")
install.packages("googlesheets4")
```

Load packages. 
```{r}
library(googlesheets4)
library(ggpubr)
library(ggeffects)
library(tidyverse)
library(readr)
library(dbplyr)
library(lubridate)
library(ggplot2)
```
OPTION 1: 
Pull spreadsheet data (.csv) off the internet via this link: https://docs.google.com/spreadsheets/d/e/2PACX-1vQKJfmHWd62rpkP21dnKIAGnMZbW7Jkf_uQXjaVSjMFQoeHi_x_NbGuH-LlsIQtmmzUJCuknTWhsuBM/pub?gid=0&single=true&output=csv
Load database into r. Note: this file will need to be redownloaded each time you want to update the data analyses, but the .csv file updates automatically online. 
```{r}
muziek_main <- read.csv("~/Downloads/Muziek - Main (2).csv") %>% 
  janitor::clean_names()

```

OPTION 2: 
Load spreadsheet data using gs4 (pull directly fromt the sheet itself).
```{r}
gs4_auth(scopes = "spreadsheets.readonly") 
# muziekspreadsheet@gmail.com <-- sign in when prompted
# muziekspreadsheet3@Tm3H@cR <-- password for google account

muziek_main <- read_sheet("https://docs.google.com/spreadsheets/d/1QH27wRqhg-6MS9vdQt7C73dLpHvsv3nov9YgxcZOlJQ/edit?pli=1&gid=0#gid=0") %>%
  janitor::clean_names()

```


Plots 
```{r}
c_rating <- ggplot(main,
       aes(x = year, y = rating)) + geom_point() + xlab("Year")  + 
  ylab("Rating")  + theme_bw()
a_rating <-  ggplot(main,
       aes(x = year, y = a_rating)) + geom_point() + xlab("Year")  + 
  ylab("Rating")  + theme_bw()
ggarrange(c_rating, a_rating, common.legend = TRUE, legend = "bottom", labels = c("A", "B"))

ggplot(main,
       aes(x = year, y = genre)) + geom_boxplot() + xlab("Year")  + 
  ylab("Genre")  + theme_bw()


```




